env:
  TERM: xterm-256color
  IS_ALACRITTY: '1' 

scrolling:
  history: 10000
  multiplier: 3

colors:
  primary:
    background: '#212431'
    foreground: '#a6accd'
    #dim_foreground: '#828482'
    #bright_foreground: '#eaeaea'
  
  cursor:
    text: CellBackground
    cursor: '#ffcc00'
  
  # Vi mode cursor colors
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  
  # Search colors
  #search:
    #matches:
    #  foreground: '#000000'
    #  background: '#ffffff'
    #focused_match:
    #  foreground: '#ffffff'
    #  background: '#000000'
    #bar:
    #  background: '#c5c8c6'
    #  foreground: '#1d1f21'

  # Keyboard regex hints
  #hints:
    #start:
    #  foreground: '#1d1f21'
    #  background: '#e9ff5e'

    #end:
    #  foreground: '#e9ff5e'
    #  background: '#1d1f21'

  # Line indicator
  #line_indicator:
  #  foreground: None
  #  background: None

  selection:
    text: CellBackground
    background: CellForeground

  # Normal colors
  normal:
    black:   '#1d1f21'
    #red:     '#cc6666'
    red:     '#ea1479'
    green:   '#b5bd68'
    #yellow:  '#f0c674'
    yellow:  '#ffcc00'
    blue:    '#81a2be'
    magenta: '#b294bb'
    cyan:    '#8abeb7'
    white:   '#c5c8c6'

  # Bright colors
  bright:
    black:   '#666666'
    red:     '#d54e53'
    green:   '#b9ca4a'
    yellow:  '#e7c547'
    blue:    '#7aa6da'
    magenta: '#c397d8'
    cyan:    '#70c0b1'
    white:   '#eaeaea'

  # Dim colors
  #dim:
  #  black:   '#131415'
  #  red:     '#864343'
  #  green:   '#777c44'
  #  yellow:  '#9e824c'
  #  blue:    '#556a7d'
  #  magenta: '#75617b'
  #  cyan:    '#5b7d78'
  #  white:   '#828482'

  # Indexed Colors
  # Example:
  #   `- { index: 16, color: '#ff00ff' }`
  #indexed_colors: []

  transparent_background_colors: false

# Bell
#bell:
  # Visual Bell Animation
  # Animation effect for flashing the screen when the visual bell is rung.
  # Values for `animation`:
  #   - Ease
  #   - EaseOut
  #   - EaseOutSine
  #   - EaseOutQuad
  #   - EaseOutCubic
  #   - EaseOutQuart
  #   - EaseOutQuint
  #   - EaseOutExpo
  #   - EaseOutCirc
  #   - Linear
  #animation: EaseOutExpo

  # Duration of the visual bell flash in milliseconds. A `duration` of `0` will
  # disable the visual bell animation.
  #duration: 0

  # Visual bell animation color.
  #color: '#ffffff'

  # Bell Command
  # This program is executed whenever the bell is rung.
  # When set to `command: None`, no command will be executed.
  #
  # Example:
  #   command:
  #     program: notify-send
  #     args: ["Hello, World!"]
  #
  #command: None

#selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  #semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When set to `true`, selected text will be copied to the primary clipboard.
  #save_to_clipboard: false

cursor:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
  style:
    shape: Underline
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: Always

  # Vi mode cursor style
  vi_mode_style: Underline 

  blink_interval: 250
  unfocused_hollow: true
  thickness: 0.45


# Live config reload (changes require restart)
live_config_reload: true

shell:
  program: /bin/zsh
  args:
    - --login

window:
  dimensions:
    columns: 175
    lines: 45

  padding:
    x: 8
    y: 4

  decorations: buttonless
  opacity: 1.0
  startup_mode: Windowed
  title: Alacritty
  dynamic_title: false

font:
  normal:
    family: MesloLGS Nerd Font
    style: Regular

  bold:
    family: MesloLGS Nerd Font
    style: Bold

  italic:
    family: Dank Mono
    style: Italic

  # Bold italic font face
  #bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    #family: monospace

    # The `style` can be specified to pick a specific face.
    #style: Bold Italic

  size: 17.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true
  builtin_box_drawing: true

draw_bold_text_with_bright_colors: false
