env:
  TERM: xterm-256color
  IS_ALACRITTY: '1' 

scrolling:
  history: 10000
  multiplier: 3

import:
  - Users/jaschavanaalst/.config/alacritty/colors.yml

# Live config reload (changes require restart)
live_config_reload: true

shell:
  program: /bin/zsh
  args:
    - --login

window:
  dimensions:
    columns: 175
    lines: 45

  padding:
    x: 8
    y: 4

  decorations: buttonless
  opacity: 1.0
  startup_mode: Windowed
  title: Alacritty
  dynamic_title: false

font:
  normal:
    family: MesloLGS Nerd Font
    style: Regular

  bold:
    family: MesloLGS Nerd Font
    style: Bold

  italic:
    family: Dank Mono
    style: Italic

  # Bold italic font face
  #bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    #family: monospace

    # The `style` can be specified to pick a specific face.
    #style: Bold Italic

  size: 17.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true
  builtin_box_drawing: true

draw_bold_text_with_bright_colors: false
