#! /usr/bin/env sh

if (( ${+_select_shell} )); then
    HEIGHT=15
    WIDTH=40
    CHOICE_HEIGHT=4
    BACKTITLE="Select \$SHELL"
    TITLE="Select \$SHELL"
    MENU="Choose one of the following options:"

    OPTIONS=(
      1 "ZShell"
      2 "Fish"
      3 "Bash"
    )

    CHOICE=$(dialog --clear \
                  --backtitle "$BACKTITLE" \
                  --title "$TITLE" \
                  --menu "$MENU" \
                  $HEIGHT $WIDTH $CHOICE_HEIGHT \
                  "${OPTIONS[@]}" \
                  2>&1 >/dev/tty)

    clear
    
    unset $_select_shell;


    case $CHOICE in
        1)
            exec fish
            ;;
        2)
            exec zsh          
            ;;
        3)

            ;;
    esac
fi

