#!/usr/bin/env zsh

gcl() {
    typeset -A shortcuts

    shortcuts=(
        ["wp"]="git@github.com:wordpress/wordpress"
    )

    if (( ${+shortcuts[$1]} )); then
        local repo="$shortcuts[$1]"
    else
        local repo="$1"
    fi

    shift

    git clone "$repo" "$@"
}

