#!/usr/bin/env zsh

function ll() {
    local ls_cmd='ls'
    local ls_args='-Ahl'

    if (( ${+LS_OVERRIDE} )); then
        ls_cmd=$LS_OVERRIDE
    fi

    if (( ${+LS_DEFAULT_ARGS} )); then
        ls_args=$LS_DEFAULT_ARGS
    fi

    eval "$ls_cmd" "$ls_args";
}
