#!/usr/bin/env zsh

ls-colors-compile() {
    local default_theme='jassie030'
    local out_path="${1:-$ZDOTDIR/.ls-colors}"
    local theme="${2:-$default_theme}"

    () {
        echo "#!/usr/bin/env zsh"
        echo ""
        echo "export LS_COLORS=\""$(vivid generate ${theme})"\";"
    } > $out_path
}
