#!/usr/bin/env zsh

function __prepend() {
	local prepended=$1
	local str=''

	while read line; do
		str="${str}"'\n'"${prepended} ${line}"
	done
    
    echo "${str}"
}

tag=$1
shift

"$@" > >(__prepend "$tag") 2> >(__prepend "$tag" 1>&2)
