#!/usr/bin/env zsh

toggle-zprof() {
    if (( ZPROF_ENABLED == 0 )); then
        echo 'export ZPROF_ENABLED=1' > "${HOME}/.zprofrc"
        echo 'zprof enabled'
    fi

    if (( ZPROF_ENABLED == 1 )); then
        echo 'export ZPROF_ENABLED=0' > "${HOME}/.zprofrc"
        echo 'zprof disabled'
    fi
}
