#!/usr/bin/env zsh

toggle-lolmsg() {
    if (( LOLMSGRC_ENABLED == 0)); then
        echo 'export LOLMSGRC_ENABLED=1' > "${HOME}/.lolmsgrc"
        echo 'lolmsg enabled'
    fi

    if (( LOLMSGRC_ENABLED == 1 )); then
        echo 'export LOLMSGRC_ENABLED=0' > "${HOME}/.lolmsgrc"
        echo 'lolmsg disabled'
    fi
}
