require 'plugins.treesitter'
require 'plugins.cmp'
require 'plugins.lualine'
require 'plugins.nvim-tree'
require 'plugins.markdown-preview'
require 'plugins.telescope'
require 'plugins.nvim-scrollbar'
require 'plugins.hop'
require 'plugins.cokeline'

