# Configuration
home: ~/.nap
default_language: sh
# theme: nord

# Colors
background: "0"
foreground: "15"
primary_color: "15"
primary_color_subdued: "11"
green: "2"
bright_green: "10"
bright_red: "9"
red: "1"
black: "8"
gray: "7" 
white: "16"
