local wezterm = require('wezterm')
local fish_args = { args = { '/usr/local/bin/fish', '--login' }, cwd = os.getenv('HOME') }

return {
    { key = 'F', mods = 'LEADER|SHIFT', action = wezterm.action({ SpawnCommandInNewTab = fish_args }) },
    { key = 'n', mods = 'SHIFT|CTRL',   action = 'ToggleFullScreen' },
    { key = 'v', mods = 'CMD',          action = wezterm.action.PasteFrom('Clipboard') },
    { key = 'c', mods = 'CMD',          action = wezterm.action.CopyTo('ClipboardAndPrimarySelection') },
    {
        key = 's',
        mods = 'LEADER',
        action = wezterm.action({
            SplitVertical = { domain = 'CurrentPaneDomain' },
        }),
    },
    {
        key = 'v',
        mods = 'LEADER',
        action = wezterm.action({
            SplitHorizontal = { domain = 'CurrentPaneDomain' },
        }),
    },
    { key = 'LeftArrow',  mods = 'ALT',          action = wezterm.action({ ActivatePaneDirection = 'Left' }) },
    { key = 'RightArrow', mods = 'ALT',          action = wezterm.action({ ActivatePaneDirection = 'Right' }) },
    { key = 'UpArrow',    mods = 'ALT',          action = wezterm.action({ ActivatePaneDirection = 'Up' }) },
    { key = 'DownArrow',  mods = 'ALT',          action = wezterm.action({ ActivatePaneDirection = 'Down' }) },
    { key = 'l',          mods = 'LEADER',       action = 'ActivateLastTab' },
    { key = 'c',          mods = 'LEADER',       action = wezterm.action({ SpawnTab = 'CurrentPaneDomain' }) },
    { key = '&',          mods = 'LEADER|SHIFT', action = wezterm.action({ CloseCurrentTab = { confirm = true } }) },
    { key = 'x',          mods = 'LEADER',       action = wezterm.action({ CloseCurrentPane = { confirm = true } }) },
    { key = 'LeftArrow',  mods = 'LEADER|SHIFT', action = wezterm.action({ AdjustPaneSize = { 'Left', 5 } }) },
    { key = 'DownArrow',  mods = 'LEADER|SHIFT', action = wezterm.action({ AdjustPaneSize = { 'Down', 5 } }) },
    { key = 'UpArrow',    mods = 'LEADER|SHIFT', action = wezterm.action({ AdjustPaneSize = { 'Up', 5 } }) },
    { key = 'RightArrow', mods = 'LEADER|SHIFT', action = wezterm.action({ AdjustPaneSize = { 'Right', 5 } }) },
    { key = '1',          mods = 'LEADER',       action = wezterm.action({ ActivateTab = 0 }) },
    { key = '2',          mods = 'LEADER',       action = wezterm.action({ ActivateTab = 1 }) },
    { key = '3',          mods = 'LEADER',       action = wezterm.action({ ActivateTab = 2 }) },
    { key = '4',          mods = 'LEADER',       action = wezterm.action({ ActivateTab = 3 }) },
    { key = '5',          mods = 'LEADER',       action = wezterm.action({ ActivateTab = 4 }) },
    { key = '6',          mods = 'LEADER',       action = wezterm.action({ ActivateTab = 5 }) },
    { key = '7',          mods = 'LEADER',       action = wezterm.action({ ActivateTab = 6 }) },
    { key = '8',          mods = 'LEADER',       action = wezterm.action({ ActivateTab = 7 }) },
    { key = '9',          mods = 'LEADER',       action = wezterm.action({ ActivateTab = 8 }) },
    { key = ']',          mods = 'CMD',          action = wezterm.action.EmitEvent('opacity-up') },
    { key = '[',          mods = 'CMD',          action = wezterm.action.EmitEvent('opacity-down') },
    { key = '=',          mods = 'CMD',          action = wezterm.action.EmitEvent('font-size-up') },
    { key = '-',          mods = 'CMD',          action = wezterm.action.EmitEvent('font-size-down') },
    { key = 'p',          mods = 'CMD',          action = wezterm.action.EmitEvent('line-height-up') },
    { key = 'o',          mods = 'CMD',          action = wezterm.action.EmitEvent('line-height-down') },
    { key = '0',          mods = 'CMD',          action = wezterm.action.EmitEvent('reset-font') },
    { key = '9',          mods = 'CMD',          action = wezterm.action.EmitEvent('toggle-font') },
    { key = 'L',          mods = 'CMD',          action = wezterm.action.ShowDebugOverlay },
}
