#!/usr/bin/env zsh

# This file is used by auto-ls, which is installed as antigen bundle.

# Default opts for ls
if ! (( ${+LS_DEFAULT_ARGS} )); then 
    export LS_DEFAULT_ARGS="-Ahl --color"
fi

# Executes ls or other prefered command.
#
# export `LS_OVERRIDE` to use other prefered command (e.g. lsd, colorls).
# export `LS_DEFAULT_ARGS` to override default args `-Ahl --color`.
function __ls_cmd () {
    (( ${+LS_OVERRIDE} )) && eval "$LS_OVERRIDE $LS_DEFAULT_ARGS" || ls  
    
    echo ""
}

# Command that is added to AUTO_LS_COMMANDS.
function auto-ls-jassies-ls {
    __ls_cmd
}

# Add based on custom config
export AUTO_LS_COMMANDS=(
    jassies-ls 
    git-status
)

