#!/usr/bin/env zsh

! (( ${+CHPWD_LS_PROGRAM} )) && export CHPWD_LS_PROGRAM="builtin ls"

! (( ${+CHPWD_LS_ARGS} )) && export CHPWD_LS_ARGS="-Ahl --color"

! (( ${+CHPWD_AUTO_LS} )) && export CHPWD_AUTO_LS=true

! (( ${+CHPWD_AUTO_GIT_STATUS} )) && export CHPWD_AUTO_GIT_STATUS=true

function __chpwd_list {
  eval $CHPWD_LS_PROGRAM "$CHPWD_LS_ARGS"
  
  [[ $CHPWD_NEWLINE != false ]] && echo ""
}

function __chpwd_git_status {
  [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == true ]] && git status
}

local _CHPWD_AUTO_CMDS=( __chpwd_git_status )

if (( ${+CHPWD_USER_COMMANDS} )); then
  export _CHPWD_AUTO_CMDS=( _chpwd_list )
fi

