#!/usr/bin/env zsh

function load_antigen {
  local antigen_path="${HOME}/antigen.zsh"
  local antigrc_path="${HOME}/.antigenrc"
  
  if [[ ! -f "$antigen_path" ]]; then 
      curl -L git.io/antigen > antigen.zsh
  fi
  
  source "$antigen_path"

  if [[ -f "$antigrc_path" ]]; then 
    antigen init "$antigrc_path"
  fi
}
