#!/usr/bin/env zsh

function lolmsg {
  local msg; local column_width; local row_height
  
  local lol_animal="lolcrab"
  local random_int=$(( ( RANDOM % 10 )  + 1 ))
  
  local is_vimterm="$1"
  local def_msg="$2"
  local alt_msg="$3"

  if [[ $random_int > 5 ]]; then
    lol_animal="lolcat"
  fi 

  [[ $is_vimterm == false ]] && msg="${def_msg}" || msg="${alt_msg}"
  
  clear
  
  echo '\n\n\n\n';

  figlet -Lcw $(tput cols) -f roman "$msg" | $lol_animal
}

