#!/usr/bin/env zsh

# Overrides from env.
(( ${+CAT_OVERRIDE} )) && alias cat=${CAT_OVERRIDE}
(( ${+LS_OVERRIDE} ))  && alias ls=${LS_OVERRIDE}

# Open cwd as project in various JetBrains IDE's
(( ${+commands[idea]} ))     && alias idea='idea .'
(( ${+commands[phpstorm]} )) && alias pstorm='phpstorm .'
(( ${+commands[webstorm]} )) && alias wstorm='webstorm .'
(( ${+commands[egrep]} ))    && alias egrep='egrep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
(( ${+commands[fgrep]} ))    && alias fgrep='fgrep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'

# Isolated php and composer
if (( ${+commands[valet]} )); then
    export DOT_VALET_BIN="$(which valet)"
    export DOT_COMPOSER_BIN="$(which composer)"

    if (( ${+commands[vphp]} )); then
        alias php='vphp'
    fi

    if (( ${+commands[vcomposer]} )); then
        alias composer='vcomposer'
    fi 
fi

if (( ${+LAZYGIT_CONFIG} )); then
    function __lazygit {
        if [[ "$(is_dark)" == 0 ]] && [[ "$(is_neovim)" == 0 ]]; then
            local config=${LAZYGIT_CONFIG}/config_light.yml
        else
            local config=${LAZYGIT_CONFIG}/config_dark.yml
        fi

        lazygit -ucf "$config" "$@"
    }

    autoload -Uz __lazygit
    alias lazygit='__lazygit'
fi

function ppgrep() { 
    pgrep "$@" | xargs ps -f -p; 
}

autoload -Uz ppgrep
