#!/usr/bin/env zsh

# Overrides from env.
(( ${+CAT_OVERRIDE} )) && alias cat=${CAT_OVERRIDE}
(( ${+LS_OVERRIDE} ))  && alias ls=${LS_OVERRIDE}

# Open cwd as project in various JetBrains IDE's
(( ${+commands[idea]} ))     && alias idea='idea .'
(( ${+commands[phpstorm]} )) && alias pstorm='phpstorm .'
(( ${+commands[webstorm]} )) && alias wstorm='webstorm .'
(( ${+commands[egrep]} ))    && alias egrep='egrep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
(( ${+commands[fgrep]} ))    && alias fgrep='fgrep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'

# Isolated php and composer
if (( ${+commands[valet]} )); then
    export DOT_VALET_BIN="$(which valet)"
    export DOT_COMPOSER_BIN="$(which composer)"

    if (( ${+commands[vphp]} )); then
        alias php='vphp'
    fi

    if (( ${+commands[vcomposer]} )); then
        alias composer='vcomposer'
    fi 
fi

if (( ${+commands[mycli]} )); then 
    function __mysql_cli {
        if [[ $# -eq 0 ]]; then
            mycli
        else
            \mariadb "$@"
        fi
    }

    autoload -Uz __mysql_cli
    alias {mariadb,mysql}='__mysql_cli'
fi

function ppgrep() { 
    pgrep "$@" | xargs ps -f -p; 
}

autoload -Uz ppgrep
