#!/usr/bin/env zsh

function _phpv {
    local version="$1"

    if [[ "$version" == 8.1 ]]; then
      version=''
    else 
      version="@$1"
    fi
    
    valet use "php$version" && composer global update
}

