#!/usr/bin/env zsh

function df_lol_msg {
  local msg; local column_width; local row_height
  
  local lol_animal="lolcrab"
  local random_int=$(( ( RANDOM % 10 )  + 1 ))
  
  local is_vimterm="$1"
  local def_msg="$2"
  local alt_msg="$3"

  if [[ $random_int > 5 ]]; then 
    lol_animal="lolcat"
  fi 

  if [[ $is_vimterm == false ]]; then 
    local msg="${def_msg}"

    column_width=$(tmux display -p '#{pane_width}') 
    row_height=$(( $(tmux display -p '#{pane_height}') )) 
  else 
    local msg="${alt_msg}"
    
    column_width=$(tput cols)
    row_height=$(( $(tput lines)+0 ))
  fi
  
  clear
  
  #for i in {1..$(( ( $row_height / 2 ) - 9 ))}; do
    echo '\n\n\n\n';
  #done

  figlet -Lcw $column_width -f "roman" $msg | $lol_animal
}

