#!/usr/bin/env zsh

# Silently start job to update dotfiles w/ RCM, calls `./rcup`
function df_start_rcup {
    setopt LOCAL_OPTIONS NO_NOTIFY NO_MONITOR   

    sh $DOTFILES/rcup &

    disown &>/dev/null
}

