#!/usr/bin/env zsh

function lolmsg {
  local lol_animal msg column_width row_height
  local random_int=$(( ( RANDOM % 10 )  + 1 ))
  
  [[ $random_int > 5 ]] && lol_animal="lolcat" || lol_animal="lolcrab"

  # Resolve msg to display
  [[ "$1" == false ]] && msg="$2" || msg="$3"
  
  # Save current output in case of warnings/errors
  tput smcup
  
  clear

  printf '\n%.0s' {1..8}

  figlet -Lcw $(tput cols) -f roman "$msg" | "$lol_animal"
  alias clear="tput rmcup; clear; unalias clear;"
}

