#!/usr/bin/env zsh

# Source a file located in $DOT_ZSH directory.
function source_zsh_dotfiles {
  local d

  for d in "$@" ; do
    [[ -f "${DOT_ZSH}/${d}" ]] && source "${DOT_ZSH}/${d}"
  done
}


