#!/usr/bin/env zsh

function toggle-lolmsg {
    if [[ "$LOLMSGRC_ENABLED" -eq 0 ]]; then
        echo 'export LOLMSGRC_ENABLED=1' > "${HOME}/.lolmsgrc"
        echo 'lolmsg enabled'
    fi

    if [[ "$LOLMSGRC_ENABLED" -eq 1 ]]; then
        echo 'export LOLMSGRC_ENABLED=0' > "${HOME}/.lolmsgrc"
        echo 'lolmsg disabled'
    fi
}
