#!/usr/bin/env zsh

# Prevent custom prompt from being sourced when running in a non-login shell.
if [[ ! -o login ]] || [[ ! -t 0 ]]; then 
    return;
fi

######################## Box Drawing Chars ################################
# U+250x	─	━	│	┃	┄	┅	┆	┇	┈	┉	┊	┋	┌	┍	┎	┏ #
# U+251x	┐	┑	┒	┓	└	┕	┖	┗	┘	┙	┚	┛	├	┝	┞	┟ #
# U+252x	┠	┡	┢	┣	┤	┥	┦	┧	┨	┩	┪	┫	┬	┭	┮	┯ #
# U+253x	┰	┱	┲	┳	┴	┵	┶	┷	┸	┹	┺	┻	┼	┽	┾	┿ #
# U+254x	╀	╁	╂	╃	╄	╅	╆	╇	╈	╉	╊	╋	╌	╍	╎	╏ #
# U+255x	═	║	╒	╓	╔	╕	╖	╗	╘	╙	╚	╛	╜	╝	╞	╟ #
# U+256x	╠	╡	╢	╣	╤	╥	╦	╧	╨	╩	╪	╫	╬	╭	╮	╯ #
# U+257x	╰	╱	╲	╳	╴	╵	╶	╷	╸	╹	╺	╻	╼	╽	╾	╿ #
###########################################################################

source ${ZDOTDIR}/prompt/helpers.zsh

autoload -Uz add-zsh-hook
autoload -Uz edit-command-line

# Use https://github.com/romkatv/gitstatus/tree/master?tab=readme-ov-file for gitstatus if available
if [[ -f "${HOME}/tools/gitstatus/gitstatus.plugin.zsh" ]]; then
    source ${ZDOTDIR}/prompt/gitstatus.prompt.zsh
    export DOT_PROMPT_BETTER_GIT_STATUS=1
else
    autoload -Uz vcs_info && add-zsh-hook precmd vcs_info

    zstyle ':vcs_info:git:*' formats '|  %b'
    zstyle ':vcs_info:git:ignore' submodule 'all'
    zstyle ':vcs_info:*' enable hg git

    export DOT_PROMPT_BETTER_GIT_STATUS=0
fi

__fpath_add "$PROMPT_FUNCTIONS_PATH"
__autoload "$PROMPT_FUNCTIONS_PATH"

# In case of meer tab gekkigheid:
# https://unix.stackexchange.com/questions/14230/zsh-tab-completion-on-empty-line
block-empty-tab() {
    if [[ ${#BUFFER//[[:blank:]]/} != 0 ]]; then
        zle fzf-completion
    fi
}

# ── fill-line cache ────────────────────────────────────────────────────────────
# All fill-line inputs are static per $COLUMNS. Cache results and invalidate on resize.
typeset -gi __PROMPT_CACHE_ENABLED=${DOT_PROMPT_CACHE_ENABLED:-1}
typeset -gi __PROMPT_CACHED_COLS=0
typeset -g  __PROMPT_CACHE_TOP=''
typeset -g  __PROMPT_CACHE_MID=''
typeset -g  __PROMPT_CACHE_COMPACT=''

__prompt_cache_invalidate() {
    __PROMPT_CACHED_COLS=0
}

__prompt_cache_rebuild() {
    (( __PROMPT_CACHE_ENABLED && COLUMNS == __PROMPT_CACHED_COLS )) && return 0

    local REPLY

    # top-prompt
    local left="%F{12}    %m %f| %F{12}  ${TERM_PROGRAM} (${TERM_PRETTY:-$TERM}) %f|%F{202} $ ${${SHELL/#\/bin\//}:u} %f"
    local right='%F{11}   %w %b |   %T   %f'
    fill-line $left $right ' '
    __PROMPT_CACHE_TOP=$REPLY

    # mid-prompt
    fill-line $PS1_TL $PS1_TR
    __PROMPT_CACHE_MID=$REPLY

    # compact-prompt
    fill-line "  ╔" '   %T'
    __PROMPT_CACHE_COMPACT=$REPLY

    if (( __PROMPT_CACHE_ENABLED )); then
        __PROMPT_CACHED_COLS=$COLUMNS
    else
        __PROMPT_CACHED_COLS=0
    fi
}

__prompt_precmd_refresh() {
    emulate -L zsh

    if (( ! __PROMPT_CACHE_ENABLED || COLUMNS != __PROMPT_CACHED_COLS )); then
        __prompt_cache_invalidate
        set-prompt
    fi
}

set-prompt() {
    emulate -L zsh

    __prompt_cache_rebuild

    local php_wgt=''
    php-ver

    local prompt_dir='%(5~|%-1~/…/%3~|%4~)'
    local git_prompt=
    if (( DOT_PROMPT_BETTER_GIT_STATUS )); then
        git_prompt='${GITSTATUS_PROMPT}'
    else
        git_prompt='%F{08}${vcs_info_msg_0_}%f'
    fi

    local bot_left="${PS1_BL} %F{13} ${prompt_dir}%f ${git_prompt} "
    local bot_right="${php_wgt} ${PS1_BR}"

    PROMPT=$'\n'${__PROMPT_CACHE_TOP}$'\n'${__PROMPT_CACHE_MID}$'\n'${bot_left}
    RPROMPT=$bot_right
}

set-compact-prompt() {
    emulate -L zsh

    __prompt_cache_rebuild

    PROMPT="%F{00}${__PROMPT_CACHE_COMPACT}"$'\n'"  ╚   %f"
    RPROMPT=''
}

zle-line-init() {
    emulate -L zsh

    [[ $CONTEXT == start ]] || return 0

    while true; do
        zle .recursive-edit
        local -i ret=$?
        [[ $ret == 0 && $KEYS == $'\4' ]] || break
        [[ -o ignore_eof ]] || exit 0
    done

    local saved_prompt=$PROMPT
    local saved_rprompt=$RPROMPT

    set-compact-prompt
    zle .reset-prompt

    PROMPT=$saved_prompt
    RPROMPT=$saved_rprompt

    if (( ret )); then
        zle .send-break
    else
        zle .accept-line
    fi

    return ret
}

bottom-redisplay() {
    emulate -L zsh

    echoti clear
    position-prompt-bottom
    zle -R
}


TRAPWINCH() {
    emulate -L zsh

    __prompt_cache_invalidate
    set-prompt

    if zle; then
        zle -I
        zle bottom-redisplay
    fi
}

() {
    emulate -L zsh

    if (( DOT_PROMPT_BETTER_GIT_STATUS )); then
        add-zsh-hook precmd gitstatus_prompt_update
    fi

    add-zsh-hook preexec position-prompt-bottom
    add-zsh-hook precmd __prompt_precmd_refresh

    zle -N zle-line-init
    zle -N bottom-redisplay
    zle -N block-empty-tab
    zle -N magic-enter
    zle -N bracketed-paste-force
    zle -N edit-command-line

    bindkey '^I' block-empty-tab
    bindkey "^M" magic-enter
    bindkey '^x' edit-command-line
    bindkey '^[[118;6u' bracketed-paste-force

    set-prompt
    clear-screen
}
