#!/usr/bin/env zsh

alias rr="exec $SHELL -l"
alias kraken='$(open gitkraken://repo/$PWD)' # Note: Don't change to double quotes, as it auto-triggers.
alias root='cd $(git rev-parse --show-toplevel)'

#------------------------------------------------ Terminal / Dotfiles ------------------------------------------------#

# Debugging
alias rscr='tput rmcup'
alias rrscr='rr && rscr'
alias rrp="exec env PROFILE_ZSHRC=1 zsh --login"
alias rrdm="exec env DOT_DISABLE_MSG=1 zsh --login"

alias checkitalics="echo -e '\e[3mitalic\e[23m'"
alias displaycolors="curl -s https://gist.githubusercontent.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/raw/ | bash"

# Controls
alias x='exit'
alias c='clear'
alias e='echo'
alias rd='rmdir'
alias edit="vim $1"

#---------------------------------------------------- Navigation -----------------------------------------------------#  

alias config="cd $XDG_CONFIG"
alias cf="config"
alias dev="cd $DEV"
alias df="cd $DOTFILES"
alias ll="ls $LS_DEFAULT_ARGS"
alias lll='ll | lolcrab'

#----------------------------------------------------- Utilities -----------------------------------------------------#  

alias brewup='brew update && brew outdated; brew upgrade && brew cleanup; brew doctor'
alias cargoup='cargo install-update --all'
alias appup='brewup && cargoup'
alias packersync="nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'"

alias tm-auto='sudo tmutil startbackup --auto; tmutil status'
alias scrsvr='open -a ScreenSaverEngine'
alias luamake="$HOME/tools/lua-language-server/3rd/luamake/luamake"

alias valetrm="rm $HOME/.config/valet/valet.sock"
alias valetr="valetrm && valet restart"

alias php74='valet use php@7.4 && composer global update'
alias php80='valet use php@8.0 && composer global update'
alias php81='valet use php && composer global update'

alias php8=php80
alias php7=php74

alias composer74="/usr/local/opt/php@7.4/bin/php $(which composer)"
alias composer80="/usr/local/opt/php@8.0/bin/php $(which composer)"
alias composer81="/usr/local/opt/php@8.1/bin/php $(which composer)"

alias pwd='echo $PWD | pbcopy'
alias fzprev="fzf --preview 'cat --color=always --style=numbers --line-range=:500 {}'"

alias list:brew="brew list"
alias list:cargo="cargo install --list"
alias list:path="echo \"$PATH\" | tr ':' '\n'"

alias lf:cargo='list:cargo | fzf'
alias lf:brew='list:brew | fzf'
alias lf:path='list:path | fzf'

alias cp:ssh="cat $HOME/.ssh/id_rsa.pub | pbcopy"
alias cp:shrug='e "¯\_(ツ)_/¯" | pbcopy'
alias cp:sbcrepo='e "{\"type\": \"composer\", \"url\": \"https://composer.sbdev.nl/\"}" | pp_json | pbcopy'
alias cp:broodje='e "38. Witte Ital. Bol Gerookte Kip, avocado mayo met extra avocado + blik cola - €9,50" | pbcopy'

alias clone:sb-starter="git clone git@bitbucket.org:socialbrothers/wordpress-starter-theme.git"
alias clone:wp="git clone git@github.com:wordpress/wordpress"

#-------------------------------------------------- Suffix Aliases ---------------------------------------------------#

alias -s php=pstorm
alias -s {.zshrc,zsh,sh,json,yaml,.env,cs,ts,html}=nvim

