#!/usr/bin/env sh

#------------------------------------------------ Terminal / Dotfiles ------------------------------------------------#

# Controls
alias z="exec zsh"
alias rr='exec $SHELL -l'
alias clear='clear-screen-zle'
alias rscr='tput rmcup'
alias rrscr='rr && rscr'

alias x='exit'
alias c='clear'
alias e='echo -n'
alias n="nvim"
alias lg="lazygit"

alias df="cd ${DOTFILES}"
alias kk="ll" # Rotating 3 keyboards, created 50/50 chance I type 'kk' instead of 'll'.
alias lll='ll | lolcrab'
alias lcount='ls | wc -l'
alias llc='lcount'

# Debugging
alias rrp="exec env PROFILE_ZSHRC=1 zsh --login"
alias rrdm="exec env DOT_DISABLE_MSG=1 zsh --login"
alias checkitalics="echo -e '\e[3mitalic\e[23m'"
alias displaycolors="curl -s https://gist.githubusercontent.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/raw/ | bash"
alias bench='hyperfine --warmup 100 "exec zsh -l"'

alias config="cd $XDG_CONFIG"
alias cf="config"
alias dev="cd ${DEV}"
alias zp="cd $ZDOTDIR/plugins/"
alias composerhome='cd $(composer -g config home)'
alias root='cd $(git rev-parse --show-toplevel)'


#----------------------------------------------------- Utilities -----------------------------------------------------#

alias luamake="$HOME/tools/lua-language-server/3rd/luamake/luamake"
alias localenv="nvim $HOME/env.local"

alias scrsvr='open -a ScreenSaverEngine'
alias tm-auto='sudo tmutil startbackup --auto; tmutil status'

alias brewup='brew update && brew outdated; brew upgrade && brew cleanup; brew doctor'
alias cargoup='cargo install-update --all'
alias appup='brewup && cargoup'

alias list:brew="brew list"
alias list:cargo="cargo install --list"
alias list:path="echo \"$PATH\" | tr ':' '\n'"

alias cp:shrug='e "¯\_(ツ)_/¯" | pbcopy'
alias cp:broodje='e "52. HUMMES-AVOCADO - witte italiaanse bol - € 6,00" | pbcopy'
alias cp:linkedin='e $LINKEDIN_PROFILE_URL | pbcopy'
alias cp:defaults='cp -r $HOME/.development/Projects/Php/Composer/jascha030/project-templates/composer-template/{.var,.phive,.editorconfig,.gitignore,.gitattributes,.phpstorm.meta.php,.php-cs-fixer.dist.php,phpunit.xml.dist,phpstan.neon.dist} $PWD/'
alias cp:fontawesome='cat $HOME/.development/Projects/Php/Wordpress/sites/sbtweema/.npmrc | pbcopy'
alias cp:composerauth='cp $HOME/.composer/auth.json ./'
alias cp:composer-bin-extras='echo "\"extra\": { \"bamarni-bin\": { \"bin-links\": false, \"forward-command\": true } }," | pbcopy'

alias wpuser:create='wp user create "jascha@socialbrothers.nl" "jascha@socialbrothers.nl" --role=administrator --user_pass="test123"'
alias wpuser:update='wp user update jascha@socialbrothers.nl --role=administrator --user_pass="test123"'
alias wpenv:user:create='wp-env run cli wp user create "jascha@socialbrothers.nl" "jascha@socialbrothers.nl" --role=administrator --user_pass="test123"'
alias wpenv:user:update='wp-env run cli wp user update jascha@socialbrothers.nl --role=administrator --user_pass="test123"'

alias valetrm="rm ${HOME}/.config/valet/*.sock"
alias valetr='valetrm && valet restart'

# Fix for Nu-shell and @antfu/ni:nu confusion
alias nup="$(which nu)"
alias nu="$HOME/.cargo/bin/nu"

kraken () { $(open gitkraken://repo/${PWD}); }

#-------------------------------------------------- Suffix Aliases ---------------------------------------------------#

alias -s php=pstorm
alias -s {.zshrc,zsh,sh,json,yaml,.env,cs,ts,html}=nvim
