#!/usr/bin/env zsh

alias rr="exec $SHELL --login"

if (( ${+LS_OVERRIDE} )); then
    alias ls=${LS_OVERRIDE}
fi

if (( ${+CAT_OVERRIDE} )); then 
    alias cat=${CAT_OVERRIDE}
fi

if (( ${+commands[nvim]} )); then 
    alias vim=nvim
fi

if (( ${+LAZYGIT_CONFIG} )); then 
    alias lazygit="lazygit -ucf ${LAZYGIT_CONFIG}"
fi 

if (( ${+commands[idea]} )); then 
    alias idea="idea ."
fi

if (( ${+commands[phpstorm]} )); then
    alias pstorm="phpstorm ."
fi

if (( ${+commands[webstorm]} )); then 
    alias wstorm="webstorm ."
fi

if (( ${+commands[egrep]} )); then
    alias egrep='egrep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
fi 

if (( ${+commands[fgrep]} )); then 
    alias fgrep='fgrep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
fi 

alias viewlog="bat -l log $1"

alias kraken='$(open gitkraken://repo/$PWD)' # Note: Don't change to double quotes, as it auto-triggers.
alias root='cd $(git rev-parse --show-toplevel)'
alias c:readme='cat $(root)/README.md'

source ${DOTFILES}/aliases

