#!/usr/bin/env zsh

#######################################################################################################################
# By Jascha030                                  Dotfiles Initialization         https://github.io/jascha030/.dotfiles #
#######################################################################################################################

if ! (( ${+XDG_CONFIG} )); then 
    export XDG_CONFIG=${HOME}/.config
fi

# antigen.zsh path. based on simple install, overwrite if installed through brew.
if ! (( ${+DOT_ANTIGEN_PATH} )); then 
    export DOT_ANTIGEN_PATH=${HOME}/antigen.zsh
fi

# .antigenrc path.
if ! (( ${+DOT_ANTIGEN_RC_PATH} )); then 
    export DOT_ANTIGEN_RC_PATH=${HOME}/.antigenrc
fi

# Alternative dir for histfiles
if ! (( ${+DOT_DATA_DIR} )); then 
    export DOT_DATA_DIR=${XDG_CONFIG}/datafiles
fi

# Prompt height in lines
if ! (( ${DOT_PROMPT_HEIGHT} )); then 
    export DOT_PROMPT_HEIGHT=2
fi

#--------------------------------------------- Internally used functions ---------------------------------------------#

function __fpath_add {
    fpath=( "$@" ${fpath[@]} )
}


function __autoload {
    local a
    for a in "$@"; do
        [[ -d "$a" ]] && autoload -Uz ${a}/*(.:t)
    done
}

function __df_load_antigen {
    # Load or install antigen
    [[ ! -f "$1" ]] && curl -L git.io/antigen > "$1"
    # Sourze antigen.zsh 
    source "$1"
    # Load rc
    [[ -f "$2" ]] && antigen init "$2"
}

#--------------------------------------------------------- Init ------------------------------------------------------#

if (( ${+DOT_COMP_DIRS} )); then 
    __fpath_add "${DOT_COMP_DIRS[@]}"
fi 

__fpath_add "${DOT_ZSH}/zfunc" "${DOT_ZSH}/completions"  
__autoload "${DOT_ZSH}/zfunc"

# Source files that are required early.
if (( ${+DOT_SOURCES} )); then 
    safe_source "${DOT_SOURCES[@]}"
fi


# Utility function, to merge arrays...
function merge_arrays {
    # undefined 
    builtin autoload -X
}

# Run and time zsh initialization 10 times.
function speedtest {
    # undefined
    builtin autoload -X
}



# Assure required dirs exist.
(( ${+DOT_REQUIRED_DIRS} )) && assert_dirs "${DOT_REQUIRED_DIRS[@]}"  

# Assure required files exist.
(( ${+DOT_REQUIRED_FILES} )) && assert_files "${DOT_REQUIRED_FILES[@]}"

# Load antigen plugins.
__df_load_antigen

# Todo: figure out how to make this more dynamic.
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
eval "$(teleport-dir init)"
eval "$(fnm env)"

# Source other zsh dotfiles like aliases etc.
if (( ${+DOT_AFTER_INIT_SOURCES} )); then 
    safe_source "${DOT_AFTER_INIT_SOURCES[@]}"
fi

# Allow to turn off lolmsg when debugging.
(( ${+DOT_DISABLE_MSG} )) && unset DOT_DISABLE_MSG || lolmsg 
