#!/usr/bin/env zsh

# Overrides from env.
(( ${+CAT_OVERRIDE} )) && alias cat=${CAT_OVERRIDE}
(( ${+LS_OVERRIDE} )) && alias ls=${LS_OVERRIDE}

(( ${+commands[idea]} ))     && alias idea='idea .'
(( ${+commands[phpstorm]} )) && alias pstorm='phpstorm .'
(( ${+commands[webstorm]} )) && alias wstorm='webstorm .'

(( ${+commands[egrep]} )) && alias egrep='egrep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
(( ${+commands[fgrep]} )) && alias fgrep='fgrep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'

function ll {
    if (( ${+LS_DEFAULT_ARGS} )); then
        eval "ls ${LS_DEFAULT_ARGS}"
    else
        ls -Ahl
    fi
}

# Copy pwd to clipboard
if (( ! $+commands[cpd] )); then
    function cpd { builtin echo -en "${PWD}" | pbcopy; }

    autoload -Uz cpd
fi

# Isolated PHP
if (( $+commands[valet] )); then
    function __iphp {
        if [[ -f "${PWD}/composer.json" ]]; then
            ${HOME}/.composer/vendor/bin/valet php "$@"
        else 
            /usr/local/bin/php "$@"
        fi
    }

    autoload -Uz __iphp
    alias php='__iphp'
fi

if (( ${+LAZYGIT_CONFIG} )); then
    function __lazygit {
        if [[ "$(is_dark)" == 0 ]] && [[ "$(is_neovim)" == 0 ]]; then
            local config=${LAZYGIT_CONFIG}/config_light.yml
        else
            local config=${LAZYGIT_CONFIG}/config_dark.yml
        fi

        lazygit -ucf "$config"
    }

    autoload -Uz __lazygit
    alias lazygit='__lazygit'
fi
