#!/usr/bin/env zsh

path=(
  /usr/local/sbin
  /usr/local/opt/openjdk/bin
  /usr/local/opt/openssl@1.1/bin
  node_modules/.bin
  vendor/bin
  ${HOME}/bin
  ${HOME}/.composer/vendor/bin
  ${HOME}/.node/bin
  ${HOME}/.yarn/bin 
  ${HOME}/.config/yarn/global/node_modules/.bin
  ${HOME}/.gem/ruby/2.6.0/bin
  ${HOME}/tools/lua-language-server/bin/macOS
  ${path[@]}
)

