#!/usr/bin/env zsh

function __position_prompt_bottom {
    local t_lines="$(echoti lines)"
    [[ $# == 0 ]] && margin=1 || margin=$((${1}))    
    echoti cup $(( (${t_lines}-${DOT_PROMPT_HEIGHT}) + $((${margin})) )) 0
}

function __clear_prompt {
    __position_prompt_bottom 2
    repeat ${DOT_PROMPT_HEIGHT} { echoti cuu1 && echoti dl1 }
}

# Add preexec hook.
autoload -Uz add-zsh-hook
add-zsh-hook preexec __clear_prompt 

clear-screen() { echoti clear; __position_prompt_bottom 2; }
clear-screen-zle() { echoti clear; __position_prompt_bottom 2; zle redisplay; }

zle -N clear-screen-zle
